import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import NavLinks from '@/ui/top-nav-links'
import Header from '@/ui/header'
import Link from 'next/link';

// const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ weight: "100",  subsets: ['latin'], style:'normal'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'main w-full h-full bg-white' + roboto.className}>
          {/* <div className='header w-full bg-l-blue px-2 py-2 flex flex-row items-end justify-between grow'>
              <span className='text-l text-dd-blue font-semibold'>
              <Link
                    key='dashboard' 
                    href='/'
                    className='mx-2 pr-1 text-dd-blue hover:text-vl-blue'
                >
                    Whampipe
                </Link>
              </span>
              <NavLinks />
          </div> */}
          <Header />
          <div className='mx-2'>{children}</div>
          {/* <div className=' h-2'>footer</div> */}
      </body>
    </html>
  )
}
